# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
/target/thickness 0.5 mm
# Initialize kernel
/run/initialize
#
#/control/verbose 2
#/run/verbose 2
#/event/verbose 0
#/tracking/verbose 1
# 

/gun/particle proton
/gun/energy 15 MeV
#/tracking/verbose 2
#
/run/beamOn 1000
