# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
#/control/verbose 2
#/run/verbose 2
#/event/verbose 0
#/tracking/verbose 1
# 
/gps/particle proton

# Position distribution: Gaussian Beam
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0. 0. -5. mm
# Sigma = 3.0mm covers ~95% within the 8.5mm target radius
/gps/pos/sigma_r 3.0 mm

# Angular distribution: Focused along Z-axis
/gps/ang/type beam1d
/gps/direction 0 0 1

# Energy distribution: Mono-energetic
/gps/ene/type Mono
/gps/ene/mono 15.0 MeV
#
/run/beamOn 1000
